name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create build directory
      run: mkdir build

    - name: Change to build directory
      run: cd build

    - name: Configure CMake
      run: cmake ./cw1

    - name: Build project
      run: make TestRun

    - name: Run tests
      run: ./TestRun
